const names=require('./names')
const sayHi=require('./func')
const data=require('./module_example')
require('./mind_grenade')
console.log(data)
console.log(names)
sayHi(names.lambu)
sayHi(names.vishnu)
sayHi(names.karthi)